field: d49a2d67-9697-4600-9b49-b221437545ce # Bottom pages
fieldLayouts:
  8486fba5-3049-47ac-a601-19e859617112:
    tabs:
      -
        elements:
          -
            fieldUid: 239b84f4-0cd5-4c13-8f6d-3660d5bd7904 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5287d825-bacb-403f-9004-2c70bdf1e2e3 # Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  239b84f4-0cd5-4c13-8f6d-3660d5bd7904: # Name
    contentColumnType: text
    fieldGroup: null
    handle: bottomPageName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  5287d825-bacb-403f-9004-2c70bdf1e2e3: # Link
    contentColumnType: text
    fieldGroup: null
    handle: bottomPageLink
    instructions: ''
    name: Link
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        7: email
        8: tel
        9: url
      autoNoReferrer: '1'
      defaultLinkName: asset
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: '1'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  -
                    - singles
                    - 'section:d53d3bce-afa8-4d8c-be8e-7f39844292ba' # Blog posts
                    - 'section:6560a834-cd10-49ce-92e8-210691efdc73' # Partners posts
                    - 'section:51c060f1-2569-4a4e-88d5-0ff236f6033b' # Podcast posts
                    - 'section:35c30890-dd01-4af7-8e09-70b7eb0d80fc' # Privacy posts
                    - 'section:06d1e5ff-4d31-4966-8bce-2bc3c44214a0' # Product posts
                    - 'section:40ccff24-98fc-4f36-bcda-88a991a455e6' # Applications posts
                -
                  - allowCustomQuery
                  - '1'
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
handle: bottomPage
name: 'Bottom page'
sortOrder: 1
