field: c89ab64b-e4c1-4c6d-93d7-44d8c24443a4 # Features list
fieldLayouts:
  a37b3646-3e05-4a66-99d3-95d59ec3e113:
    tabs:
      -
        elements:
          -
            fieldUid: e331def1-cf12-4b55-ac22-2ac11fc15200 # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9dcf980f-b542-4d32-9ffc-7b8bfbc00d2b # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b344aae0-3626-410e-9952-96da19bd3d07 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9dcf980f-b542-4d32-9ffc-7b8bfbc00d2b: # Title
    contentColumnType: text
    fieldGroup: null
    handle: featureTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b344aae0-3626-410e-9952-96da19bd3d07: # Description
    contentColumnType: text
    fieldGroup: null
    handle: featureDescription
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e331def1-cf12-4b55-ac22-2ac11fc15200: # Icon
    contentColumnType: string
    fieldGroup: null
    handle: featureIcon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: feature
name: Feature
sortOrder: 1
