field: f53cbe83-0ab1-40b6-b1ab-b3fb95b0338f # Images
fieldLayouts:
  ac23d0f1-9d06-40c6-b8f0-227fb4e1e8e6:
    tabs:
      -
        elements:
          -
            fieldUid: 08614d3a-fe80-46d8-8bdf-1ca8c8860ccc # Asset
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 998d961f-669a-4df1-acf5-c61e3bf61762 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  998d961f-669a-4df1-acf5-c61e3bf61762: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: imageTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  08614d3a-fe80-46d8-8bdf-1ca8c8860ccc: # Asset
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageAsset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 1
