field: 1e7613e1-69f5-49da-82f7-f940e639a542 # Carousel images
fieldLayouts:
  7c6d96c8-0e92-4a7b-874a-af7900c11a19:
    tabs:
      -
        elements:
          -
            fieldUid: 5724bb4e-d769-43f8-aefd-beecbfaff77c # Item image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6e1a1771-b046-4c09-b97a-b8ef34a8e872 # Item text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6e1a1771-b046-4c09-b97a-b8ef34a8e872: # Item text
    columnSuffix: icsfwpdh
    contentColumnType: text
    fieldGroup: null
    handle: itemText
    instructions: ''
    name: 'Item text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5724bb4e-d769-43f8-aefd-beecbfaff77c: # Item image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: ''
    name: 'Item image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: item
name: Item
sortOrder: 1
