field: dcd7d559-2862-495d-8cf1-52ee98241609 # Links
fieldLayouts:
  a6580853-498f-452a-980d-278bdafdaa69:
    tabs:
      -
        elements:
          -
            fieldUid: 188c33ac-460b-4d12-b08b-109b7c0b67a3 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d429f357-c49a-4947-9ea7-dcc9b7e56816 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  188c33ac-460b-4d12-b08b-109b7c0b67a3: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: ''
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d429f357-c49a-4947-9ea7-dcc9b7e56816: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        7: email
        8: tel
        9: url
      autoNoReferrer: '1'
      defaultLinkName: asset
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: '1'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  -
                    - singles
                    - 'section:d53d3bce-afa8-4d8c-be8e-7f39844292ba' # Blog posts
                    - 'section:6560a834-cd10-49ce-92e8-210691efdc73' # Partners posts
                    - 'section:51c060f1-2569-4a4e-88d5-0ff236f6033b' # Podcast posts
                    - 'section:06d1e5ff-4d31-4966-8bce-2bc3c44214a0' # Product posts
                    - 'section:40ccff24-98fc-4f36-bcda-88a991a455e6' # Applications posts
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
handle: item
name: item
sortOrder: 1
