field: f54e51cf-0116-4f13-a320-a3a439d30f85 # Items
fieldLayouts:
  33e8aed8-5c6a-4c7e-bc70-6c2c0613f69d:
    tabs:
      -
        elements:
          -
            fieldUid: 187be502-d66f-4151-8d84-60d39af8e06a # Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 94f9fd80-5d01-4419-824e-d719a55b4e96 # Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0b5a77dd-12dc-41c7-81ce-277a415dcde3 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a0f0651b-ebc3-439d-81de-edb79696d474 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b5a77dd-12dc-41c7-81ce-277a415dcde3: # Description
    contentColumnType: text
    fieldGroup: null
    handle: itemDescription
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  94f9fd80-5d01-4419-824e-d719a55b4e96: # Name
    contentColumnType: text
    fieldGroup: null
    handle: itemName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  187be502-d66f-4151-8d84-60d39af8e06a: # Icon
    contentColumnType: string
    fieldGroup: null
    handle: itemIcon
    instructions: ''
    name: Icon
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  a0f0651b-ebc3-439d-81de-edb79696d474: # Buttons
    contentColumnType: string
    fieldGroup: null
    handle: itemButtonsMatrix
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 09dac1e7-92a8-4090-9811-6f99033a0244 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_30_itembuttonsmatrix}}'
      fieldLayout: table
      maxRows: '2'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: item
name: Item
sortOrder: 1
