field: 48557ce9-6791-4592-8f05-1e5bef9fc217 # Accordion List
fieldLayouts:
  96170a36-8fca-4bfe-8804-649ba196a00a:
    tabs:
      -
        elements:
          -
            fieldUid: d39a7676-3993-4cc9-93e4-297573aef493 # Accordion Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 32828d37-1aa3-4b9a-82e8-bf3f6178c337 # Accordion Item Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9025b0d5-90f0-4270-9520-0397b1cbc0d6 # Accordion Item Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  32828d37-1aa3-4b9a-82e8-bf3f6178c337: # Accordion Item Subtitle
    contentColumnType: text
    fieldGroup: null
    handle: accordionItemSubtitle
    instructions: ''
    name: 'Accordion Item Subtitle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9025b0d5-90f0-4270-9520-0397b1cbc0d6: # Accordion Item Image
    contentColumnType: string
    fieldGroup: null
    handle: accordionItemImage
    instructions: ''
    name: 'Accordion Item Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  d39a7676-3993-4cc9-93e4-297573aef493: # Accordion Item Title
    contentColumnType: text
    fieldGroup: null
    handle: accordionItemTitle
    instructions: ''
    name: 'Accordion Item Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: Item
sortOrder: 1
