field: 5eab1f92-40f5-468b-806f-344696ecca4b # Logos Slider Items
fieldLayouts:
  43084c69-be0e-49bc-98c1-3a52f4ea4631:
    tabs:
      -
        elements:
          -
            fieldUid: b70a6a9e-3ca3-4d53-a836-f30d51f6c58e # Item Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0cb15938-ac86-4efb-a156-55003949c82a # Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 856cff78-8d18-4dfb-ae45-f4c779296ee6 # Item link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0cb15938-ac86-4efb-a156-55003949c82a: # Item Title
    contentColumnType: text
    fieldGroup: null
    handle: itemTitle
    instructions: ''
    name: 'Item Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  856cff78-8d18-4dfb-ae45-f4c779296ee6: # Item link
    contentColumnType: string(255)
    fieldGroup: null
    handle: itemLink
    instructions: 'Url to Company / Article '
    name: 'Item link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b70a6a9e-3ca3-4d53-a836-f30d51f6c58e: # Item Image
    contentColumnType: string
    fieldGroup: null
    handle: itemImage
    instructions: ''
    name: 'Item Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: item
name: Item
sortOrder: 1
