field: 9eb6a3d4-968c-4aee-b6bd-7bad0d20065a # Accordion List
fieldLayouts:
  0f36b257-7e33-4afd-a7eb-c21f73b1b342:
    tabs:
      -
        elements:
          -
            fieldUid: 8cef4245-c176-42e2-9fce-2ebddd03b4ff # Accordion Item Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3810de6e-16a1-4209-a56f-89f2017bf9c0 # Accordion Item Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0d19a1fa-434e-42c8-91b3-267af6ff4d61 # Accordion Item Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0d19a1fa-434e-42c8-91b3-267af6ff4d61: # Accordion Item Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: accordionItemImage
    instructions: ''
    name: 'Accordion Item Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: 1
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  8cef4245-c176-42e2-9fce-2ebddd03b4ff: # Accordion Item Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: accordionItemTitle
    instructions: ''
    name: 'Accordion Item Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  3810de6e-16a1-4209-a56f-89f2017bf9c0: # Accordion Item Subtitle
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: accordionItemSubtitle
    instructions: ''
    name: 'Accordion Item Subtitle'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: item
name: Item
sortOrder: 1
