field: 98991cd5-c9c4-41b3-9e68-2b31b44bd772 # Partners list
fieldLayouts:
  9e918aae-9a5c-44f0-a19e-1e07d1b7fef0:
    tabs:
      -
        elements:
          -
            fieldUid: de2f137b-e43d-43ff-8b36-31978ed3eef1 # Partner logo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c7c9f302-4f23-466d-a2d3-675621d8f44a # Partner Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b7ac79ba-352c-490e-aaa7-737c89d9e247 # Partner description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6be2d726-24c6-4a93-8d7c-30a8b9da7b06 # Partner Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a187bb9-ebd0-4016-b111-84d728762249 # Partner category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0a187bb9-ebd0-4016-b111-84d728762249: # Partner category
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: partnerCategory
    instructions: 'Press ctrl (cmd) or Shift to select multiple values'
    name: 'Partner category'
    searchable: false
    settings:
      multi: true
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Inlay & Tag'
            -
              - value
              - inlayTag
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Printer
            -
              - value
              - printer
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Serialization
            -
              - value
              - serialization
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Solution Provider'
            -
              - value
              - solutionProvider
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Wi-Fi Access Point Gateway'
            -
              - value
              - wiFiAccessPointGateway
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Consulting
            -
              - value
              - consulting
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MultiSelect
  6be2d726-24c6-4a93-8d7c-30a8b9da7b06: # Partner Link
    columnSuffix: null
    contentColumnType: string(255)
    fieldGroup: null
    handle: partnerLink
    instructions: ''
    name: 'Partner Link'
    searchable: false
    settings:
      maxLength: '255'
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  b7ac79ba-352c-490e-aaa7-737c89d9e247: # Partner description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: partnerDescription
    instructions: ''
    name: 'Partner description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c7c9f302-4f23-466d-a2d3-675621d8f44a: # Partner Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: partnerName
    instructions: ''
    name: 'Partner Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  de2f137b-e43d-43ff-8b36-31978ed3eef1: # Partner logo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: partnerLogo
    instructions: ''
    name: 'Partner logo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: item
name: Item
sortOrder: 1
