field: 20fd2ce4-fdf9-4c30-a769-05745f8760b1 # Founders list
fieldLayouts:
  8b9961e1-bc54-43fa-9283-e5e5bfea5d0d:
    tabs:
      -
        elements:
          -
            fieldUid: e9d050a2-d6ba-4905-b800-ca89d3b5b612 # Person name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 40d03163-36d4-4f35-8a30-a5fff1e8a7a7 # Person title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2a49d969-0dee-48a1-8c68-ccfdaf603d25 # Person linkedin link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2a49d969-0dee-48a1-8c68-ccfdaf603d25: # Person linkedin link
    contentColumnType: text
    fieldGroup: null
    handle: personLinkedinLink
    instructions: ''
    name: 'Person linkedin link'
    searchable: false
    settings:
      allowCustomText: 1
      allowTarget: ''
      allowedLinkNames: '*'
      autoNoReferrer: ''
      defaultLinkName: url
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  40d03163-36d4-4f35-8a30-a5fff1e8a7a7: # Person title
    contentColumnType: text
    fieldGroup: null
    handle: personTitle
    instructions: ''
    name: 'Person title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e9d050a2-d6ba-4905-b800-ca89d3b5b612: # Person name
    contentColumnType: text
    fieldGroup: null
    handle: personName
    instructions: ''
    name: 'Person name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: person
name: Person
sortOrder: 1
