field: 1e1f8be2-6b6c-46d2-9c81-9a714e68cf8b # Freemode Slider Items
fieldLayouts:
  b347b0c2-7070-4048-b9ed-504e9f69270a:
    tabs:
      -
        elements:
          -
            fieldUid: fef447a5-6f16-41ec-b9d1-06eae787b40b # Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ab90bdf-5ff3-41ea-831b-684ff05d1cce # Slide Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2a9ad26-9dc8-4db2-86d9-765a45ec74bd # Slide Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ec440ae-2546-41fe-9045-81df8f5f5f5b # Slide Codes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9ab90bdf-5ff3-41ea-831b-684ff05d1cce: # Slide Description
    contentColumnType: text
    fieldGroup: null
    handle: slideDescription
    instructions: ''
    name: 'Slide Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9ec440ae-2546-41fe-9045-81df8f5f5f5b: # Slide Codes
    contentColumnType: string
    fieldGroup: null
    handle: slideCodes
    instructions: ''
    name: 'Slide Codes'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 456e69dd-efa5-4424-9a70-99829afcad2f # Code
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_8_slidecodes}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  e2a9ad26-9dc8-4db2-86d9-765a45ec74bd: # Slide Button Link
    contentColumnType: text
    fieldGroup: null
    handle: slideButtonLink
    instructions: ''
    name: 'Slide Button Link'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        7: email
        8: tel
        9: url
      autoNoReferrer: '1'
      defaultLinkName: entry
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: '1'
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  -
                    - singles
                    - 'section:d53d3bce-afa8-4d8c-be8e-7f39844292ba' # Blog posts
                    - 'section:6560a834-cd10-49ce-92e8-210691efdc73' # Partners posts
                    - 'section:51c060f1-2569-4a4e-88d5-0ff236f6033b' # Podcast posts
                    - 'section:35c30890-dd01-4af7-8e09-70b7eb0d80fc' # Privacy posts
                    - 'section:06d1e5ff-4d31-4966-8bce-2bc3c44214a0' # Product posts
                    - 'section:40ccff24-98fc-4f36-bcda-88a991a455e6' # Solutions posts
                -
                  - allowCustomQuery
                  - ''
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  fef447a5-6f16-41ec-b9d1-06eae787b40b: # Slide Title
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: 'Slide Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: slide
name: Slide
sortOrder: 1
