field: 1e1f8be2-6b6c-46d2-9c81-9a714e68cf8b # Freemode Slider Items
fieldLayouts:
  b347b0c2-7070-4048-b9ed-504e9f69270a:
    tabs:
      -
        elements:
          -
            fieldUid: fef447a5-6f16-41ec-b9d1-06eae787b40b # Slide Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ab90bdf-5ff3-41ea-831b-684ff05d1cce # Slide Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e2a9ad26-9dc8-4db2-86d9-765a45ec74bd # Slide Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9ec440ae-2546-41fe-9045-81df8f5f5f5b # Slide Codes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9ab90bdf-5ff3-41ea-831b-684ff05d1cce: # Slide Description
    contentColumnType: text
    fieldGroup: null
    handle: slideDescription
    instructions: ''
    name: 'Slide Description'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  9ec440ae-2546-41fe-9045-81df8f5f5f5b: # Slide Codes
    contentColumnType: string
    fieldGroup: null
    handle: slideCodes
    instructions: ''
    name: 'Slide Codes'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - ad25b9ac-bb0a-4131-a915-eb2e3b845882 # Code
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_slidecodes}}'
      fieldLayout: matrix
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  e2a9ad26-9dc8-4db2-86d9-765a45ec74bd: # Slide Button Link
    contentColumnType: string(255)
    fieldGroup: null
    handle: slideButtonLink
    instructions: ''
    name: 'Slide Button Link'
    searchable: false
    settings:
      maxLength: 255
      placeholder: null
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  fef447a5-6f16-41ec-b9d1-06eae787b40b: # Slide Title
    contentColumnType: text
    fieldGroup: null
    handle: slideTitle
    instructions: ''
    name: 'Slide Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: 4
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: slide
name: Slide
sortOrder: 1
