field: 9f228b4c-f012-484c-8615-377f81df9e68 # Steps
fieldLayouts:
  e1a7ca37-e62e-4633-bcf4-f3706d14cc9e:
    tabs:
      -
        elements:
          -
            fieldUid: 5281c3a0-348a-46a8-8c45-1baf9799132d # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a486e38a-51ed-4d5d-bf72-d04b328035cb # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 87177607-5716-4279-8237-b2ba94bc541c # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5281c3a0-348a-46a8-8c45-1baf9799132d: # Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepTitle
    instructions: ''
    name: Title
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  87177607-5716-4279-8237-b2ba94bc541c: # Button
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepButton
    instructions: 'Fill this field if You want to see a button under the text.'
    name: Button
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      allowedLinkNames:
        3: entry
        9: url
      autoNoReferrer: '1'
      defaultLinkName: url
      defaultText: ''
      enableAriaLabel: ''
      enableTitle: ''
      typeSettings:
        __assoc__:
          -
            - asset
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - category
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - entry
            -
              __assoc__:
                -
                  - sources
                  -
                    - singles
                    - 'section:40ccff24-98fc-4f36-bcda-88a991a455e6' # Applications posts
                    - 'section:d53d3bce-afa8-4d8c-be8e-7f39844292ba' # Blog posts
                    - 'section:6560a834-cd10-49ce-92e8-210691efdc73' # Partners posts
                    - 'section:51c060f1-2569-4a4e-88d5-0ff236f6033b' # Podcast posts
                    - 'section:35c30890-dd01-4af7-8e09-70b7eb0d80fc' # Privacy posts
                    - 'section:06d1e5ff-4d31-4966-8bce-2bc3c44214a0' # Product posts
                -
                  - allowCustomQuery
                  - '1'
          -
            - site
            -
              __assoc__:
                -
                  - sites
                  - '*'
          -
            - user
            -
              __assoc__:
                -
                  - sources
                  - '*'
                -
                  - allowCustomQuery
                  - ''
          -
            - custom
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - email
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - tel
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
          -
            - url
            -
              __assoc__:
                -
                  - disableValidation
                  - ''
                -
                  - allowAliases
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: typedlinkfield\fields\LinkField
  a486e38a-51ed-4d5d-bf72-d04b328035cb: # Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: stepDescription
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: step
name: Step
sortOrder: 1
