fieldLayouts:
  cd226af3-a720-488f-b832-b1cb24b57703:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 569c1536-e1e1-478b-8a94-de85377f9ba0 # Hero sizes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 070c859e-ec54-49e9-acd9-e658f728d891 # Hero subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70e371d8-d7fb-43ef-a3fc-913faa7db3d1 # Hero tItle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 7892f1d0-1d11-4392-b6f6-8203d8a025ab # Bubbles title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: efd18ac7-76d0-467e-9ab9-36f697e0a185 # Bubbles subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dff21a29-e991-4ee9-8765-8622ff096925 # Bubbles Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7a38c6ed-e2bf-4b5c-905f-7d8e236ceaab # Bubbles Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 401dea4c-31e6-46a8-b3a2-a109796af24c # Bubbles Footnote
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f95d261d-1a3d-4d0a-9d41-737859b8039c # Bubbles List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Who We Are'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 42c9bf17-7aff-4618-8490-da905c7c9c43 # Founders title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b28d5854-c7e5-4852-8520-e188e64a2631 # Founders image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9fa974e7-3590-48d6-8a42-e0acc5f366f6 # Founders list
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Founders
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 4318cfd0-f068-4073-9703-1db060485eb7 # Outro Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ba42799d-0a49-4f7f-817a-cde956fa12ee # Outro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 977b9cb6-8f53-45bc-84f4-62dddeecf971 # Outro subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Outro
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 1eaaafbd-b179-4945-90ab-bcbedcaef599 # Accordion title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48557ce9-6791-4592-8f05-1e5bef9fc217 # Accordion List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Awards & Recognitions'
        sortOrder: 6
      -
        elements:
          -
            fieldUid: 019acba1-844e-4207-9e1f-e3614724e436 # Freemode Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 06a2a62d-5870-4c21-bb82-9d2ca4c782ac # Freemode Slider Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Certifications & Qualifications'
        sortOrder: 7
      -
        elements:
          -
            fieldUid: 58e82b15-a8b8-4b1d-b541-06330a0b14af # Logos Slider Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6857bdeb-bd05-44af-8217-cacf876bea09 # Logos Slider Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 550cf2c2-19f9-45cd-ab55-1231e5e06dc2 # Logos Slider Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2ab81306-e636-4739-b674-9a2c704fff7c # Logos Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Our Partners'
        sortOrder: 8
handle: company
hasTitleField: false
name: Company
section: 72d02a55-6c6b-4589-ae2c-3028c14e0ba6 # Company
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
