fieldLayouts:
  6ebabfa6-01a2-40bf-bff2-3c8e821b8738:
    tabs:
      -
        elements:
          -
            fieldUid: 345b4661-88c3-4313-a1b2-3f233f9f8884 # Meta title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66244511-52d0-45cd-86d3-415cb109cfbb # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Meta tags'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 569c1536-e1e1-478b-8a94-de85377f9ba0 # Hero sizes
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 070c859e-ec54-49e9-acd9-e658f728d891 # Hero subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 70e371d8-d7fb-43ef-a3fc-913faa7db3d1 # Hero tItle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 3
      -
        elements:
          -
            fieldUid: f83f711c-531c-4ea9-954e-ec67c966c6e4 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2ea61b1b-f641-40be-bc12-c76a4ab3957d # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a1d858b7-4963-496f-9423-33546a166a0a # Centered Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e4dface-74fb-48c5-9710-06f194b7baa6 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 404edfb5-6c67-47db-b78e-83080fabe753 # Video Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Who We Are'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 9c0236e8-b45d-426d-a9ef-98e1a28bffac # Carousel subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 728a5398-9579-432c-9347-232326dedb3b # Carousel Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e7613e1-69f5-49da-82f7-f940e639a542 # Carousel images
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Image Carousel'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: fd6828c8-bfe1-4a5b-bc60-81cbd0a5b91a # Founders title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 939f5fba-03cc-4d0d-842f-55aaab58ee13 # Founders image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 20fd2ce4-fdf9-4c30-a769-05745f8760b1 # Founders list
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Founders
        sortOrder: 6
      -
        elements:
          -
            fieldUid: 289339c7-e182-4952-86da-d0c42b30519e # Logos Slider Button Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 27470b2f-bd24-4902-9cc9-0ae02ba6d8b4 # Logos Show Arrows
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5eab1f92-40f5-468b-806f-344696ecca4b # Logos Slider Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f4561c6e-39fa-472f-90d8-3e5873d7a32a # Logos Slider Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35e076cc-710f-4084-b0a3-4052d9d1476c # Logos Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Our Partners'
        sortOrder: 7
      -
        elements:
          -
            fieldUid: 61810cd1-a5ad-48ca-b484-28ea81b52efc # Accordion title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9eb6a3d4-968c-4aee-b6bd-7bad0d20065a # Accordion List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Awards & Recognitions'
        sortOrder: 8
      -
        elements:
          -
            fieldUid: c07974ee-0ece-431d-80f0-1b44b35a7fa6 # Freemode Slider Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e1f8be2-6b6c-46d2-9c81-9a714e68cf8b # Freemode Slider Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Certifications & Qualifications'
        sortOrder: 9
      -
        elements:
          -
            fieldUid: 4318cfd0-f068-4073-9703-1db060485eb7 # Outro Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ba42799d-0a49-4f7f-817a-cde956fa12ee # Outro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 105018f4-b231-4a6d-bfd1-bd253f36173b # Outro subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Outro
        sortOrder: 10
handle: company
hasTitleField: false
name: Company
section: 1cb6c681-bbc6-4442-b924-71726e4d56e0 # Company
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
