fieldLayouts:
  44e3e72c-4848-4190-ac6e-f14529e1a73d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 43c3ac2c-5537-41c8-8d85-38897d5163a3 # Page link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 102fa206-3e00-4a9f-a145-9848b1eb4449 # Subnav Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: menuDesktop
hasTitleField: true
name: 'Menu - desktop'
section: 2199390b-1fa8-4a3a-8fe0-4cd1fad2370d # Menu - desktop
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
