fieldLayouts:
  4b27edbf-c484-4af1-89a1-ee53b80cf64b:
    tabs:
      -
        elements:
          -
            fieldUid: 345b4661-88c3-4313-a1b2-3f233f9f8884 # Meta title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66244511-52d0-45cd-86d3-415cb109cfbb # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Meta tags'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 19e14f84-94c7-4ee4-9cd0-c5502ad3dcf8 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a6bb284-4bb7-433a-b923-6a73511b00e3 # Episode number
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 08c08a19-7586-4f73-8dcd-e05ee43122b5 # Excerpt
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3a4a422a-dc9c-4197-9077-e92ec024187f # Iframe widget title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 04f4064e-282d-4747-b723-a1919a0e7984 # Iframe Widget
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e18c7120-cd43-475e-99a5-a9b566fcb443 # Video ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8608b72a-4d71-486a-a8c5-05de9f86f6da # Hero button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a404d7db-a8ee-45b9-be68-9316c6209368 # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 919d4ce0-d5c1-46c0-ad7c-9757ccd75260 # Transcript
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: f57c7759-562c-46f3-978a-20ba7fde1d0e # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2e55047-197c-4f1d-ab5f-083fb740855a # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 34734b74-001f-4710-8e8b-224354eb86f9 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Subscribe
        sortOrder: 3
handle: podcastDetails
hasTitleField: true
name: 'Podcast Details'
section: 51c060f1-2569-4a4e-88d5-0ff236f6033b # Podcast posts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
