fieldLayouts:
  072b6095-4ddb-442a-8f01-88240fe77846:
    tabs:
      -
        elements:
          -
            fieldUid: 345b4661-88c3-4313-a1b2-3f233f9f8884 # Meta title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66244511-52d0-45cd-86d3-415cb109cfbb # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Meta tags'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 2d82d9f8-9f42-4103-8889-38c6b53fd72f # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4fc213ec-173b-4fc8-a72e-59017eeb1418 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 3
      -
        elements:
          -
            fieldUid: fb9317cd-b414-4e68-a951-161864e164da # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 067352cf-49f4-4653-9bf5-b16cdba55ed4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c1ea5f92-9656-4dcc-be98-4f72c644a75a # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57d48c6b-6881-45af-9650-f9eae5956900 # Items
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Accordions
        sortOrder: 4
      -
        elements:
          -
            fieldUid: 51850a96-c233-45ae-930f-6eda18372ebe # Rows
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Products list'
        sortOrder: 5
      -
        elements:
          -
            fieldUid: d111e5db-7197-4cec-a5e6-6a9e02fca730 # Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d0210b1c-0e4d-4821-a924-8c593285b2a0 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 28534271-d900-4661-aef7-3c72a4e3ac85 # List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Use Cases'
        sortOrder: 6
      -
        elements:
          -
            fieldUid: ba42799d-0a49-4f7f-817a-cde956fa12ee # Outro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7637ec1c-947f-42f2-9b7d-3ba65f195b8d # Outro Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4318cfd0-f068-4073-9703-1db060485eb7 # Outro Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Outro
        sortOrder: 7
handle: products
hasTitleField: false
name: 'Wiliot Platform'
section: a20376e6-81c6-4ecc-8014-c22eac87de16 # Wiliot Platform
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
