fieldLayouts:
  ca853343-9ff3-4892-9784-c57fd9cddf9c:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: f3ab10b4-5d6a-4c83-9a65-ca0ab0346314 # Intro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0515b35-e39d-4154-bb06-ea6904427257 # Intro Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Intro
        sortOrder: 2
handle: singlePodcast
hasTitleField: true
name: 'Single podcast'
section: d53d3bce-afa8-4d8c-be8e-7f39844292ba # Blog posts
sortOrder: 2
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
