fieldLayouts:
  efe9bc2a-82c0-4cb8-978d-4ccabc30468f:
    tabs:
      -
        elements:
          -
            fieldUid: 345b4661-88c3-4313-a1b2-3f233f9f8884 # Meta title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66244511-52d0-45cd-86d3-415cb109cfbb # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Meta tags'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Name
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 6ea0a802-91c1-4b0a-9c1c-fe9dd9a1475d # Solution hero subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 12270e35-d7e1-48a1-b8cf-863adc972d30 # Solution hero title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a87aa858-2e9d-4ac5-be71-84ee0f3747a1 # Solution Hero buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4885e560-0d9b-452b-a66f-509ef5402bcf # Solution hero image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Hero
        sortOrder: 3
      -
        elements:
          -
            fieldUid: fc578d10-4d6e-4d97-8780-ffbb58c217b1 # Solutions hero bottom title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6f796f5-c843-4d77-bd6d-f2570cdb5dfe # Solution hero bottom description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d18ce51-463e-4721-bc7b-a8c1aa470f3c # Solution hero bottom image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Hero bottom'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: cb1ba679-0805-4bee-a515-986f9e17282a # Solution content subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a67bb8c1-3f20-4333-98ad-c87efbbfe01d # Solution content title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 56b8df8b-8895-49c6-b0af-465e722997dd # Solution Tab
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Tabs
        sortOrder: 6
      -
        elements:
          -
            fieldUid: 32dcf3c9-68d5-496c-879b-13b735cd8709 # Video File
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Video
        sortOrder: 7
      -
        elements:
          -
            fieldUid: ba42799d-0a49-4f7f-817a-cde956fa12ee # Outro Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7637ec1c-947f-42f2-9b7d-3ba65f195b8d # Outro Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4318cfd0-f068-4073-9703-1db060485eb7 # Outro Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6b2ff6ec-480b-4eaf-b69a-c4c50f6a38c5 # Outro Button 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Outro
        sortOrder: 8
handle: solutionsDetails
hasTitleField: true
name: 'Solutions details'
section: 40ccff24-98fc-4f36-bcda-88a991a455e6 # Applications posts
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
