fieldLayouts:
  0619a4a7-ce75-40a8-bdce-e04039492bad:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: partnersCategories
name: 'Partners categories'
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    hasUrls: true
    template: null
    uriFormat: 'partners-categories/{slug}'
structure:
  maxLevels: null
  uid: 17edf758-360a-4e02-b4f9-baacad303dfb
