// SCRIPTS
import './scripts/partnersFilters';
import './scripts/accordion';
import './scripts/bubbles';
import './scripts/buyTilesIcons';
import './scripts/loadMore';
// OLD
import './scripts/sliders';
import './scripts/doge';
