// SCRIPTS
import './scripts/header';
import './scripts/menuMobile';
import './scripts/partnersFilters';
import './scripts/video';
import './scripts/accordion';
import './scripts/bubbles';
import './scripts/buyTilesIcons';
import './scripts/loadMore';
import './scripts/sliding-boxes';
import './scripts/solutionsDetails';
import './scripts/bgShape';
// OLD
import './scripts/sliders';
import './scripts/doge';
