columnSuffix: null
contentColumnType: text
fieldGroup: c099bea2-dca9-43e8-9d52-a90262f58489 # Accordion Text
handle: accordionTextSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
