contentColumnType: text
fieldGroup: 2f5bdbd3-15bd-4ec2-a037-ab0fae726b21 # Accordion
handle: accordionTitle
instructions: ''
name: 'Accordion title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
