contentColumnType: string
fieldGroup: c099bea2-dca9-43e8-9d52-a90262f58489 # Accordion Text
handle: accordionTextItems
instructions: ''
name: Items
searchable: false
settings:
  contentTable: '{{%matrixcontent_accordiontextitems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
