columnSuffix: null
contentColumnType: string
fieldGroup: 136967b6-0b63-42be-b995-f4f39ebbbaa2 # Cards
handle: cardsButtonsMatrix
instructions: ''
name: 'Bottom buttons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_cardsbuttonsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
