contentColumnType: string
fieldGroup: f98b36eb-f334-4b82-ab68-6b2c373e65bd # Careers Listing
handle: careersItemsMatrix
instructions: ''
name: 'Careers items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_careersitemsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
