columnSuffix: ysvsalcv
contentColumnType: text
fieldGroup: 6b34756b-1dbb-483b-a22f-fba6464b8a65 # Carousel
handle: carouselTitle
instructions: ''
name: 'Carousel Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
