columnSuffix: null
contentColumnType: string
fieldGroup: 6b34756b-1dbb-483b-a22f-fba6464b8a65 # Carousel
handle: carouselImages
instructions: ''
name: 'Carousel items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_carouselimages}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
