columnSuffix: null
contentColumnType: string
fieldGroup: 21d49cb5-ea4c-47f8-968f-1f576d33384b # Contact
handle: contactLinksMatrix
instructions: ''
name: Links
searchable: false
settings:
  contentTable: '{{%matrixcontent_contactlinksmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
