contentColumnType: string
fieldGroup: 21d49cb5-ea4c-47f8-968f-1f576d33384b # Contact
handle: contactOffices
instructions: ''
name: Offices
searchable: false
settings:
  contentTable: '{{%matrixcontent_contactoffices}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
