contentColumnType: text
fieldGroup: 21d49cb5-ea4c-47f8-968f-1f576d33384b # Contact
handle: contactSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
