columnSuffix: null
contentColumnType: text
fieldGroup: 3483b78f-a9c7-4d75-87dd-d628b350d850 # Featured podcast
handle: featuredPodcastSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
