contentColumnType: text
fieldGroup: e093f00b-b0d5-4920-872a-d85762062655 # Fifty Fifty
handle: fiftyFiftySubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
