columnSuffix: null
contentColumnType: string
fieldGroup: e093f00b-b0d5-4920-872a-d85762062655 # Fifty Fifty
handle: fiftyFiftyNumeration
instructions: ''
name: Numeration
searchable: false
settings:
  multi: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Show rows numeration'
        -
          - value
          - 'true'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
