columnSuffix: null
contentColumnType: string
fieldGroup: f2e4a9f3-d27e-41c6-85bd-d9ae093c6d13 # Founders
handle: foundersList
instructions: ''
name: 'Founders list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_founderslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
