contentColumnType: string
fieldGroup: d383c208-ea3c-4268-82cf-50feb6c9e73e # Freemode Slider
handle: freemodeSliderItems
instructions: ''
name: 'Freemode Slider Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_freemodeslideritems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
