columnSuffix: null
contentColumnType: string
fieldGroup: e087f7d2-bc23-487f-b41c-8d92f33af71b # Freemode Slider
handle: freemodeSliderItems
instructions: ''
name: 'Freemode Slider Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_freemodeslideritems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
