columnSuffix: null
contentColumnType: string
fieldGroup: 83a380f9-0f52-4434-a9f9-dfcd5c8a80c9 # Hero
handle: heroButtonsMatrix
instructions: ''
name: 'Hero buttons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_herobuttonsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
