columnSuffix: null
contentColumnType: text
fieldGroup: 83a380f9-0f52-4434-a9f9-dfcd5c8a80c9 # Hero
handle: heroTitle
instructions: ''
name: 'Hero tItle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: TItle
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
