columnSuffix: null
contentColumnType: string
fieldGroup: 063e6186-1a4a-4b67-8c0b-313b878562a1 # Login tiles
handle: loginTilesMatrix
instructions: ''
name: Items
searchable: false
settings:
  contentTable: '{{%matrixcontent_logintilesmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
