columnSuffix: null
contentColumnType: string
fieldGroup: d07372ba-d1d9-4dd7-8445-876845e91761 # Logos Slider
handle: logosSliderShowArrows
instructions: ''
name: 'Logos Show Arrows'
searchable: false
settings:
  multi: true
  options:
    -
      __assoc__:
        -
          - label
          - 'Show Arrows'
        -
          - value
          - 'true'
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Checkboxes
