contentColumnType: text
fieldGroup: 2384fde5-5487-4da7-9bc5-d0c133e64cd8 # Menu - desktop
handle: menuDesktopSubnavTitle
instructions: ''
name: 'Subnav title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
