columnSuffix: null
contentColumnType: string
fieldGroup: 2384fde5-5487-4da7-9bc5-d0c133e64cd8 # Menu - desktop
handle: menuDesktopButtonsMatrix
instructions: ''
name: Buttons
searchable: false
settings:
  contentTable: '{{%matrixcontent_menudesktopbuttonsmatrix}}'
  maxBlocks: '3'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
