contentColumnType: text
fieldGroup: 3bc314b7-43b1-424b-9982-93a1dfd51e61 # Menu - mobile
handle: menuMobilePageLink
instructions: ''
name: 'Page link'
searchable: false
settings:
  allowCustomText: ''
  allowTarget: '1'
  allowedLinkNames:
    3: entry
    9: url
  autoNoReferrer: '1'
  defaultLinkName: asset
  defaultText: ''
  enableAriaLabel: ''
  enableTitle: ''
  typeSettings:
    __assoc__:
      -
        - asset
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - category
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - entry
        -
          __assoc__:
            -
              - sources
              -
                - singles
                - 'section:d53d3bce-afa8-4d8c-be8e-7f39844292ba' # News posts
                - 'section:6560a834-cd10-49ce-92e8-210691efdc73' # Partners details
                - 'section:40ccff24-98fc-4f36-bcda-88a991a455e6' # Solutions details
            -
              - allowCustomQuery
              - ''
      -
        - site
        -
          __assoc__:
            -
              - sites
              - '*'
      -
        - user
        -
          __assoc__:
            -
              - sources
              - '*'
            -
              - allowCustomQuery
              - ''
      -
        - custom
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - email
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - tel
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
      -
        - url
        -
          __assoc__:
            -
              - disableValidation
              - ''
            -
              - allowAliases
              - ''
translationKeyFormat: null
translationMethod: none
type: typedlinkfield\fields\LinkField
