columnSuffix: null
contentColumnType: text
fieldGroup: 1539e223-b771-4778-a5b9-3676b59a2508 # Outro
handle: outroTitle
instructions: Title
name: 'Outro Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
