columnSuffix: null
contentColumnType: string
fieldGroup: dd858d53-47d5-4810-a42f-393db932e0d1 # Partners slider
handle: partnersSliderItemsMatrix
instructions: ''
name: Items
searchable: false
settings:
  contentTable: '{{%matrixcontent_partnersslideritemsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
