columnSuffix: yifwofrm
contentColumnType: text
fieldGroup: 0d21acff-592d-40fb-830e-41732066f9a2 # Partners slider
handle: partnersSliderTitle
instructions: ''
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
