columnSuffix: null
contentColumnType: text
fieldGroup: 8602fbce-3eeb-4f22-9810-f375fc887896 # Partners details
handle: partnerFormOutroTitle
instructions: 'Title over the form. (If blank the title would say: "Interested?")'
name: 'Form Outro Title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: 'Interested?'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
