contentColumnType: string
fieldGroup: c6882d8c-7b75-4033-97e8-bb0a0d47c7c4 # Partners listing
handle: partnersList
instructions: ''
name: 'Partners list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_partnerslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
