columnSuffix: owcgxwyl
contentColumnType: text
fieldGroup: dd858d53-47d5-4810-a42f-393db932e0d1 # Partners slider
handle: partnersSliderSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
