contentColumnType: text
fieldGroup: 124f1ea9-b5e3-4adb-9255-3494228579eb # Podcast details
handle: podcastDetailsIframeTitle
instructions: "Enter title text over Podcast Widget \r\n(if blank - Title is taken from Globals -> Podcasts -> Iframe widget title)"
name: 'Iframe widget title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
