contentColumnType: string
fieldGroup: 124f1ea9-b5e3-4adb-9255-3494228579eb # Podcast details
handle: podcastDetailsTranscript
instructions: ''
name: Transcript
searchable: false
settings:
  contentTable: '{{%matrixcontent_podcastdetailstranscript}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
