columnSuffix: ajkwckhl
contentColumnType: text
fieldGroup: 5bd5b61d-261c-4edc-b7d5-db9d19898adf # Popup
handle: popupBottomSubtitle
instructions: ''
name: 'Popup bottom subtitle'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
