columnSuffix: null
contentColumnType: string
fieldGroup: e3c519dc-ffda-4163-9281-94d48fae4a97 # Press Kit
handle: pressKitVideos
instructions: ''
name: Videos
searchable: false
settings:
  contentTable: '{{%matrixcontent_presskitvideos}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
