columnSuffix: null
contentColumnType: string
fieldGroup: de1163dd-8313-4726-9b06-b94751f20bcf # Product features
handle: productFeaturesList
instructions: ''
name: 'Features list'
searchable: false
settings:
  contentTable: '{{%matrixcontent_productfeatureslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
