columnSuffix: null
contentColumnType: text
fieldGroup: 2a6a4e3f-35a1-4dd1-bddd-8988e6201dfb # Solutions globals
handle: relatedSolutionsTitle
instructions: ''
name: 'Related Solutions title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
