columnSuffix: null
contentColumnType: string
fieldGroup: 82d102f3-bac9-465b-acb7-b017dd02a99d # Sliding Boxes
handle: slidingBoxesList
instructions: 'Max 5 boxes'
name: List
searchable: false
settings:
  contentTable: '{{%matrixcontent_slidingboxeslist}}'
  maxBlocks: '5'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
