columnSuffix: null
contentColumnType: text
fieldGroup: b1158f56-1d48-4daa-8dd9-c1bba3f2fac7 # Solutions details
handle: solutionContentTitle
instructions: ''
name: 'Solution content title'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
