contentColumnType: string
fieldGroup: b1158f56-1d48-4daa-8dd9-c1bba3f2fac7 # Solutions details
handle: solutionTabMatrix
instructions: ''
name: 'Solution Tab'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 16200484-3340-49e2-9ab2-ab50d535a73b # Name
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 213988ad-d3c4-410c-beb6-b839faee1650 # Solution Tab item
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_solutiontabmatrix}}'
  fieldLayout: matrix
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: ''
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
