contentColumnType: string
fieldGroup: b1158f56-1d48-4daa-8dd9-c1bba3f2fac7 # Solutions details
handle: solutionButtonsMatrix
instructions: ''
name: 'Solution Hero buttons'
searchable: false
settings:
  contentTable: '{{%matrixcontent_solutionbuttonsmatrix}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
