columnSuffix: null
contentColumnType: string
fieldGroup: 9e586bd4-a970-4bc6-925c-4a0a46f168e8 # Tabs
handle: tabsList
instructions: ''
name: List
searchable: false
settings:
  contentTable: '{{%matrixcontent_tabslist}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
