columnSuffix: qvberdyb
contentColumnType: text
fieldGroup: 459cdd6c-927a-4e04-b971-bddef82a6209 # Text Photo
handle: textPhotoSubtitle
instructions: ''
name: Subtitle
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
