columnSuffix: null
contentColumnType: string
fieldGroup: d884b922-16a7-4812-90d0-dddd3c2c50d8 # Text and Photo
handle: TextAndPhotoImage
instructions: ''
name: Image
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
  defaultUploadLocationSubpath: ''
  limit: 1
  localizeRelations: false
  previewMode: full
  restrictFiles: ''
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:9609ca58-e35b-42d2-914a-4865163ca851' # Main
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
