columnSuffix: jhrimblr
contentColumnType: text
fieldGroup: d884b922-16a7-4812-90d0-dddd3c2c50d8 # Text and Photo
handle: TextAndPhotoText
instructions: ''
name: Text
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: 4
  multiline: 1
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
