columnSuffix: eukrfkgx
contentColumnType: text
fieldGroup: 98f0aaaf-2d44-47db-9fa1-8098294bb87b # Two boxes
handle: twoBoxesTitle
instructions: ''
name: Title
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
