columnSuffix: null
contentColumnType: string
fieldGroup: 93057504-4085-4034-82c7-fe50bb491e6e # Two boxes
handle: twoBoxesMatrix
instructions: ''
name: Items
searchable: false
settings:
  contentTable: '{{%matrixcontent_twoboxesmatrix}}'
  maxBlocks: '2'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
