columnSuffix: null
contentColumnType: string
fieldGroup: 98f0aaaf-2d44-47db-9fa1-8098294bb87b # Two boxes
handle: twoBoxesMatrix
instructions: ''
name: Items
searchable: false
settings:
  contentTable: '{{%matrixcontent_twoboxesmatrix}}'
  maxBlocks: '2'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
