columnSuffix: null
contentColumnType: string
fieldGroup: 857c6863-c09d-40d1-ad6b-84766ed728aa # Videos
handle: videos
instructions: ''
name: Videos
searchable: false
settings:
  contentTable: '{{%matrixcontent_videos}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
