field: 9ec440ae-2546-41fe-9045-81df8f5f5f5b # Slide Codes
fieldLayouts:
  cea83009-70d7-48b4-8de9-4071c01ddfe2:
    tabs:
      -
        elements:
          -
            fieldUid: 456e69dd-efa5-4424-9a70-99829afcad2f # Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  456e69dd-efa5-4424-9a70-99829afcad2f: # Code
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: code
    instructions: ''
    name: Code
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
