field: 56b8df8b-8895-49c6-b0af-465e722997dd # Solution Tab
fieldLayouts:
  705d2611-9831-4ce6-874d-a1c96062a37b:
    tabs:
      -
        elements:
          -
            fieldUid: 16200484-3340-49e2-9ab2-ab50d535a73b # Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 213988ad-d3c4-410c-beb6-b839faee1650 # Solution Tab item
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  213988ad-d3c4-410c-beb6-b839faee1650: # Solution Tab item
    contentColumnType: string
    fieldGroup: null
    handle: solutionTabItemMatrix
    instructions: ''
    name: 'Solution Tab item'
    searchable: false
    settings:
      contentTable: '{{%matrixcontent_solutiontabitemmatrix}}'
      maxBlocks: ''
      minBlocks: ''
      propagationMethod: all
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Matrix
  16200484-3340-49e2-9ab2-ab50d535a73b: # Name
    contentColumnType: text
    fieldGroup: null
    handle: solutionTabName
    instructions: ''
    name: Name
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
