field: a3b937be-4645-4775-a711-630eb62205b7 # Item content
fieldLayouts:
  27eafe83-6831-4590-8621-c036fefa6f38:
    tabs:
      -
        elements:
          -
            fieldUid: bb28a450-0555-4dfd-adcf-19215e1cb556 # Item content title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4515f842-a5c0-45ca-8972-db451c1d41e7 # Item content description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4515f842-a5c0-45ca-8972-db451c1d41e7: # Item content description
    contentColumnType: text
    fieldGroup: null
    handle: itemContentDescription
    instructions: ''
    name: 'Item content description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: ''
      redactorConfig: ''
      removeEmptyTags: ''
      removeInlineStyles: ''
      removeNbsp: ''
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  bb28a450-0555-4dfd-adcf-19215e1cb556: # Item content title
    contentColumnType: text
    fieldGroup: null
    handle: itemContentTitle
    instructions: ''
    name: 'Item content title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
