fieldLayouts:
  4898ccea-d468-4372-893d-5521e5ebfdf4:
    tabs:
      -
        elements:
          -
            fieldUid: 345b4661-88c3-4313-a1b2-3f233f9f8884 # Meta title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 66244511-52d0-45cd-86d3-415cb109cfbb # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'SEO Meta tags'
        sortOrder: 1
handle: globalMetaTags
name: 'SEO Meta tags'
sortOrder: 5
