fieldLayouts:
  f8b40bc5-ec22-4064-a6ec-0d7946f4d6ef:
    tabs:
      -
        elements:
          -
            fieldUid: e0f40b19-dd3b-4f18-a99b-99a5eee0dea3 # Socials
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Socials
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d49a2d67-9697-4600-9b49-b221437545ce # Bottom pages
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Bottom pages'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: fe9bbee7-6b39-41b4-adbd-62f98271d906 # Logos
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Logos
        sortOrder: 3
handle: pageOptions
name: 'Page Options'
