defaultPlacement: end
enableVersioning: true
handle: contact
name: Contact
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: pages/contact
    uriFormat: contact
type: single
