enableVersioning: true
handle: menuDesktop
name: 'Menu - desktop'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: menu-desktop/_entry
    uriFormat: 'menu-desktop/{slug}'
structure:
  maxLevels: null
  uid: f81c763b-b600-4fea-b894-447d5c8908ea
type: structure
