enableVersioning: true
handle: menuFooter
name: 'Menu - footer'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: menu-footer/_entry
    uriFormat: 'menu-footer/{slug}'
structure:
  maxLevels: null
  uid: 73cd6074-a579-4d16-86dd-a0676ecd57f2
type: structure
