defaultPlacement: end
enableVersioning: true
handle: partnerProgram
name: 'Partner program'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: pages/partner-program
    uriFormat: partner-program
type: single
