enableVersioning: true
handle: podcastDetails
name: 'Podcast Details'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: pages/podcast-details
    uriFormat: 'podcasts/{slug}'
type: channel
