defaultPlacement: end
enableVersioning: true
handle: purchaseSurvey
name: 'Purchase Survey'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: pages/purchase-survey
    uriFormat: purchase-survey
type: single
