defaultPlacement: end
enableVersioning: true
handle: thankYou
name: 'Thank you'
propagationMethod: all
siteSettings:
  37de40b8-92bb-49a3-a07a-6f27ac6c2fb5: # Wiliot
    enabledByDefault: true
    hasUrls: true
    template: pages/thank-you
    uriFormat: thank-you
type: single
